<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="53174" started-at="2019-03-14T10:17:13Z" finished-at="2019-03-14T10:18:06Z">
    <groups>
    </groups>
    <test name="Invalid Login Test" duration-ms="34541" started-at="2019-03-14T10:17:13Z" finished-at="2019-03-14T10:17:47Z">
      <class name="testCase.logintestcase.InvalidLoginTest">
        <test-method status="PASS" signature="initiatebrowser()[pri:0, instance:testCase.logintestcase.InvalidLoginTest@20e2cbe0]" name="initiatebrowser" is-config="true" duration-ms="12568" started-at="2019-03-14T18:17:13Z" finished-at="2019-03-14T18:17:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiatebrowser -->
        <test-method status="PASS" signature="invalidLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testCase.logintestcase.InvalidLoginTest@20e2cbe0]" name="invalidLoginTest" duration-ms="9910" started-at="2019-03-14T18:17:26Z" data-provider="Invalid Login Authentication" finished-at="2019-03-14T18:17:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santhi.asusvivobook@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method status="PASS" signature="invalidLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testCase.logintestcase.InvalidLoginTest@20e2cbe0]" name="invalidLoginTest" duration-ms="11309" started-at="2019-03-14T18:17:36Z" data-provider="Invalid Login Authentication" finished-at="2019-03-14T18:17:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santhi@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[automation123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method status="PASS" signature="signout()[pri:0, instance:testCase.logintestcase.InvalidLoginTest@20e2cbe0]" name="signout" is-config="true" duration-ms="47" started-at="2019-03-14T18:17:47Z" finished-at="2019-03-14T18:17:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
      </class> <!-- testCase.logintestcase.InvalidLoginTest -->
    </test> <!-- Invalid Login Test -->
    <test name="Valid Login Test" duration-ms="6376" started-at="2019-03-14T10:17:47Z" finished-at="2019-03-14T10:17:54Z">
      <class name="testCase.logintestcase.ValidLoginTest">
        <test-method status="PASS" signature="initiatebrowser()[pri:0, instance:testCase.logintestcase.ValidLoginTest@3e6fa38a]" name="initiatebrowser" is-config="true" duration-ms="6330" started-at="2019-03-14T18:17:47Z" finished-at="2019-03-14T18:17:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiatebrowser -->
        <test-method status="FAIL" signature="validLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testCase.logintestcase.ValidLoginTest@3e6fa38a]" name="validLoginTest" duration-ms="1" started-at="2019-03-14T18:17:54Z" data-provider="Valid Login Authentication" finished-at="2019-03-14T18:17:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santhi.asusvivobook@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[automation123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testCase.logintestcase.ValidLoginTest.validLoginTest(ValidLoginTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="signout()[pri:0, instance:testCase.logintestcase.ValidLoginTest@3e6fa38a]" name="signout" is-config="true" duration-ms="12" started-at="2019-03-14T18:17:54Z" finished-at="2019-03-14T18:17:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
      </class> <!-- testCase.logintestcase.ValidLoginTest -->
    </test> <!-- Valid Login Test -->
    <test name="Verify MyAccountPage Test" duration-ms="12108" started-at="2019-03-14T10:17:54Z" finished-at="2019-03-14T10:18:06Z">
      <class name="testCase.myaccounttestcase.MyaccountTC">
        <test-method status="FAIL" signature="verifyMyAccountpage()[pri:0, instance:testCase.myaccounttestcase.MyaccountTC@91161c7]" name="verifyMyAccountpage" duration-ms="46" started-at="2019-03-14T18:18:06Z" finished-at="2019-03-14T18:18:06Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at actionscript.MyAccountPageScript.checkMyAccountheaderandnavigation(MyAccountPageScript.java:16)
	at testCase.myaccounttestcase.MyaccountTC.verifyMyAccountpage(MyaccountTC.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMyAccountpage -->
      </class> <!-- testCase.myaccounttestcase.MyaccountTC -->
      <class name="testCase.logintestcase.ValidLoginTest">
        <test-method status="PASS" signature="start(java.lang.String)[pri:0, instance:testCase.logintestcase.ValidLoginTest@5c3bd550]" name="start" is-config="true" duration-ms="4508" started-at="2019-03-14T18:17:08Z" finished-at="2019-03-14T18:17:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="initiatebrowser()[pri:0, instance:testCase.logintestcase.ValidLoginTest@5c3bd550]" name="initiatebrowser" is-config="true" duration-ms="12025" started-at="2019-03-14T18:17:54Z" finished-at="2019-03-14T18:18:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiatebrowser -->
        <test-method status="FAIL" signature="validLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testCase.logintestcase.ValidLoginTest@5c3bd550]" name="validLoginTest" duration-ms="1" started-at="2019-03-14T18:18:06Z" data-provider="Valid Login Authentication" finished-at="2019-03-14T18:18:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santhi.asusvivobook@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[automation123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testCase.logintestcase.ValidLoginTest.validLoginTest(ValidLoginTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="signout()[pri:0, instance:testCase.logintestcase.ValidLoginTest@5c3bd550]" name="signout" is-config="true" duration-ms="15" started-at="2019-03-14T18:18:06Z" finished-at="2019-03-14T18:18:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testCase.logintestcase.ValidLoginTest@5c3bd550]" name="teardown" is-config="true" duration-ms="682" started-at="2019-03-14T18:18:06Z" finished-at="2019-03-14T18:18:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCase.logintestcase.ValidLoginTest -->
    </test> <!-- Verify MyAccountPage Test -->
  </suite> <!-- Suite -->
</testng-results>
